--CREATE DATABASE MandiolaWebService
USE MandiolaWebService

CREATE TABLE [dbo].[COMPRA_EASY_PAY](
   [NUM_CUENTA] NVARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [CODIGO_SEGURIDAD] NVARCHAR(10) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [FONDOS] NVARCHAR(50) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [CONTRASENA_CUENTA] VARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
 CONSTRAINT [PK_COMPRA_EASY_PAY] PRIMARY KEY CLUSTERED
(
    [NUM_CUENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[COMPRA_TARJETA_DEBITO_CREDITO](
   [NUM_TARJETA] VARCHAR(16) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [MES_EXPIRACION] NVARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [ANO_EXPIRACION] NVARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [CVV] NVARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [SALDO] NVARCHAR(50) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [TIPO] VARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
   [MARCA] NVARCHAR(20) COLLATE Latin1_General_BIN2 
   ENCRYPTED WITH (
	COLUMN_ENCRYPTION_KEY = CEK1,
	ENCRYPTION_TYPE = Deterministic,
	ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
   )not null,
 CONSTRAINT [PK_COMPRA_TARJETA_DEBITO_CREDI] PRIMARY KEY CLUSTERED
(
    [NUM_TARJETA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
